name: Docker Image CI
run-name: ${{ github.actor }} is creating a docker image when there is a change in master

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: Build Docker Image when push to master/dev
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    needs: super-lint  # Ensure this runs only if super-lint passes

    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
